title: Raghu Chittersu
logo: /assets/img/logo.png
description: I am Masters student at Departent of Computational and Data Sciences, Indian Institute of Science, Bengelauru. I am part of Machine and Languange Learning Lab
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
