title: Raghu Chittersu
logo: /assets/img/logo.png
description: I am a member of Machine and Language Learning Lab(MALL), IISc. I am working on problems related to Natural Language Understanding. In my free time I often read books.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
